### ISSUE TITLE
Can't Play Again After Give Up

### ISSUE THREAD

**Issue by p-shah** [tdinh7/Jumble#6]
![image](https://user-images.githubusercontent.com/8657183/32921763-ca4d4092-cafc-11e7-9a6e-666e102c11a7.png)

**Comment by Pourush1** [comment]
the game would restart to the beginning after you click give up button.

**Comment by jaitken** [comment]
Able to reproduce this bug by completing a game and starting again, next time you hit the give up button it will break the button and game
